# Model
model = "deepseek-v4-flash"
model_provider = "deepseek"
model_reasoning_effort = "low"

forced_login_method = "api"
model_context_window = 1048576
model_auto_compact_token_limit = 850000
model_auto_compact_token_limit_scope = "total"
tool_output_token_limit = 50000

sandbox_mode = "workspace-write"
approval_policy = "never"
allow_login_shell = true


# DeepSeek Provider
[model_providers.deepseek]
name = "DeepSeek"
base_url = "https://api.deepseek.com"
wire_api = "responses"
env_key = "DEEPSEEK_API_KEY"
requires_openai_auth = false
request_max_retries = 3
stream_max_retries = 3
stream_idle_timeout_ms = 120000


[sandbox_workspace_write]
network_access = true


# MCP
[mcp_servers.fersk-mcp-server]
url = "http://127.0.0.1:8000/mcp"
enabled = false
required = true
startup_timeout_ms = 10000
tool_timeout_sec = 120
supports_parallel_tool_calls = true


# Memory
[memories]
generate_memories = true
use_memories = true
extract_model = "deepseek-v4-flash"
consolidation_model = "deepseek-v4-flash"
min_rollout_idle_hours = 24
max_rollout_age_days = 30
max_unused_days = 90
max_rollouts_per_startup = 16
max_raw_memories_for_consolidation = 256
disable_on_external_context = true


# History
[history]
persistence = "save-all"
max_bytes = 104857600

[projects."/home/fersk/fersk_codex"]
trust_level = "trusted"

[projects."/home/fersk/.codex/workspace/on_72a05ca4bff2716266215ad002cf276c"]
trust_level = "trusted"

[projects."/home/fersk/.codex/workspace/on_18cf7a2a88c26bb853d54270e18c1d9d"]
trust_level = "trusted"

[marketplaces.codex-observability-plugin]
last_updated = "2026-09-08T02:35:18Z"
last_revision = "1db5c0f5ddce569afc112c6476e21d00cf9a482e"
source_type = "git"
source = "https://github.com/langfuse/codex-observability-plugin.git"

[plugins."tracing@codex-observability-plugin"]
enabled = true

[features]
plugin_hooks = true

[hooks.state]

[hooks.state."tracing@codex-observability-plugin:hooks/hooks.json:stop:0:0"]
trusted_hash = "sha256:69a05cbfa6984ec5f1433343b45480d5239c119e7332ae863f9865edc2efec74"
