notify = ["/Users/fersk/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]
model = "gpt-6-astra"
model_reasoning_effort = "medium"
service_tier = "default"

[desktop]
followUpQueueMode = "steer"
conversationDetailMode = "STEPS_COMMANDS"
preventSleepWhileRunning = true
show-context-window-usage = true

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/fersk/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/fersk/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.codex-observability-plugin]
last_updated = "2026-09-09T10:17:26Z"
last_revision = "1db5c0f5ddce569afc112c6476e21d00cf9a482e"
source_type = "git"
source = "https://github.com/langfuse/codex-observability-plugin.git"

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."tracing@codex-observability-plugin"]
enabled = true

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/fersk/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/fersk/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.911.61220"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/fersk/.codex/plugins/cache/openai-bundled/browser/26.911.61220/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/fersk/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[mcp_servers.fersk-mcp]
url = "http://fersk-mcp:8000/mcp"

[features]
plugin_hooks = true

[hooks.state]

[hooks.state."tracing@codex-observability-plugin:hooks/hooks.json:stop:0:0"]
enabled = true
trusted_hash = "sha256:69a05cbfa6984ec5f1433343b45480d5239c119e7332ae863f9865edc2efec74"

[projects."/Users/fersk/Documents/skills-office"]
trust_level = "trusted"

[projects."/Users/fersk/Documents/fersk"]
trust_level = "trusted"

[projects."/home/app"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_72a05ca4bff2716266215ad002cf276c"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/oc_03c16dc313c0c37e7dd7dc8e8de2dbad"]
trust_level = "trusted"

[projects."/Users/fersk/OrbStack/ubuntu/home/fersk/fersk_mcp"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_18cf7a2a88c26bb853d54270e18c1d9d"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_d6ce39b714886434cb949513c17aa8aa"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_7233a0e7fd8734b669f6876f4692ae62"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_eaa3f831c38b4fbdbc844d63ee1da3bb"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_d74059a70abe96815f35be169920b8e7"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_7dbd9f4206f49e1857bbe91d1c2a355b"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/on_b8e9267f0c33f33e27c26811451a4d6c"]
trust_level = "trusted"

[projects."/home/app/.codex/workspace/oc_7a10ffbc4e5d181406e0f24b34ae89c9"]
trust_level = "trusted"

[projects."/home/app/test"]
trust_level = "trusted"
