[project]
name = "fersk_mcp"
version = "0.1.0"
description = "Fersk MCP server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lark-oapi>=1.7.3",
    "mcp>=2.2.0",
    "openai>=3.10.0",
    "python-dotenv>=1.0.0",
    "jsonschema>=4.0.0",
]

[project.scripts]
fersk-mcp = "fersk_mcp.server:main"

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true

[tool.setuptools]
packages = [
    "fersk_mcp",
    "fersk_mcp.configs",
    "fersk_mcp.utils",
    "fersk_mcp.tools",
    "fersk_mcp.tools.internal_tools",
    "fersk_mcp.tools.lark_tools",
]
package-dir = { fersk_mcp = "." }

[tool.setuptools.package-data]
fersk_mcp = ["configs/*.json"]
